-- Create "groups" table

CREATE TABLE
    "groups" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY ("id")
    );

-- Create "users" table

CREATE TABLE
    "users" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "username" character varying NOT NULL,
        "password" character varying NOT NULL,
        "email" character varying NOT NULL,
        PRIMARY KEY ("id")
    );

-- Create index "users_email_key" to table: "users"

CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");

-- Create index "users_username_key" to table: "users"

CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");

-- Create "books" table

CREATE TABLE
    "books" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "title" character varying NOT NULL,
        "description" character varying NOT NULL,
        "user_books" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "books_users_books" FOREIGN KEY ("user_books") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE
        SET NULL
    );

-- Create "chapters" table

CREATE TABLE
    "chapters" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "title" character varying NOT NULL,
        "description" character varying NOT NULL,
        "book_chapters" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "chapters_books_chapters" FOREIGN KEY ("book_chapters") REFERENCES "books" ("id") ON UPDATE NO ACTION ON DELETE
        SET NULL
    );

-- Create "pages" table

CREATE TABLE
    "pages" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "title" character varying NOT NULL,
        "content" character varying NOT NULL,
        "chapter_pages" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "pages_chapters_pages" FOREIGN KEY ("chapter_pages") REFERENCES "chapters" ("id") ON UPDATE NO ACTION ON DELETE
        SET NULL
    );

-- Create "todos" table

CREATE TABLE
    "todos" (
        "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "create_time" timestamptz NOT NULL,
        "update_time" timestamptz NOT NULL,
        "title" character varying NOT NULL,
        "description" character varying NOT NULL,
        "status" boolean NOT NULL DEFAULT false,
        "book_todos" bigint NULL,
        "chapter_todos" bigint NULL,
        "page_todos" bigint NULL,
        "user_todos" bigint NULL,
        PRIMARY KEY ("id"),
        CONSTRAINT "todos_books_todos" FOREIGN KEY ("book_todos") REFERENCES "books" ("id") ON UPDATE NO ACTION ON DELETE
        SET
            NULL,
            CONSTRAINT "todos_chapters_todos" FOREIGN KEY ("chapter_todos") REFERENCES "chapters" ("id") ON UPDATE NO ACTION ON DELETE
        SET
            NULL,
            CONSTRAINT "todos_pages_todos" FOREIGN KEY ("page_todos") REFERENCES "pages" ("id") ON UPDATE NO ACTION ON DELETE
        SET
            NULL,
            CONSTRAINT "todos_users_todos" FOREIGN KEY ("user_todos") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE
        SET NULL
    );