// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
